"""Netlist writers for parasitic extraction results.

Supported output formats:
- SPICE (.spice) — subcircuit with devices + parasitic R/C elements
- SPEF (.spef) — Standard Parasitic Exchange Format (IEEE 1481)
- Spectre (.scs) — Cadence Spectre netlist format

All writers now produce a complete netlist containing:
1. Original devices (transistors, resistors, capacitors, etc.)
2. Parasitic resistors (wire segments and vias)
3. Parasitic capacitors (substrate and inter-net coupling)
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from pathlib import Path

from .extractor import DeviceInstance, ExtractionResult, ParasiticCapacitor, ParasiticResistor

logger = logging.getLogger(__name__)


class NetlistWriter(ABC):
    """Base class for netlist output writers."""

    @abstractmethod
    def write(self, result: ExtractionResult, output_path: Path) -> None:
        """Write extraction results to a file."""
        ...


class SpiceWriter(NetlistWriter):
    """Write parasitic netlist in SPICE format.

    Output format:
        .subckt <cell_name> <ports>
        * --- Devices ---
        XI0 node1 node2 ... model param=val ...
        * --- Parasitic Resistances ---
        R1 node1 node2 <value>
        * --- Parasitic Capacitances ---
        C1 node1 0 <value>f
        .ends
    """

    def write(self, result: ExtractionResult, output_path: Path) -> None:
        lines: list[str] = []
        lines.append(f"* Parasitic RC extraction: {result.cell_name}")
        lines.append("* Generated by rcextract")
        lines.append("*")
        lines.append(f"* Devices: {len(result.devices)}")
        lines.append(f"* Resistors: {result.total_r}")
        lines.append(f"* Capacitors: {result.total_c}")
        lines.append("")

        # Subcircuit header
        ports_str = " ".join(result.ports)
        lines.append(f".subckt {result.cell_name} {ports_str}")
        lines.append("")

        # Devices
        if result.devices:
            lines.append("* --- Devices ---")
            for dev in result.devices:
                line = _format_spice_device(dev)
                lines.append(line)
            lines.append("")

        # Resistors
        if result.resistors:
            r_count = 0
            lines.append("* --- Parasitic Resistances ---")
            for resistor in result.resistors:
                r_count += 1
                node1 = _sanitize_node(resistor.node1)
                node2 = _sanitize_node(resistor.node2)
                lines.append(f"R{r_count} {node1} {node2} {resistor.value:.4g}")
            lines.append("")

        # Capacitors
        if result.capacitors:
            c_count = 0
            lines.append("* --- Parasitic Capacitances ---")
            for cap in result.capacitors:
                c_count += 1
                node1 = _sanitize_node(cap.node1)
                node2 = _sanitize_node(cap.node2)
                lines.append(f"C{c_count} {node1} {node2} {cap.value:.4g}f")
            lines.append("")

        lines.append(f".ends {result.cell_name}")
        lines.append("")

        output_path.write_text("\n".join(lines))
        logger.info(f"SPICE: wrote {len(result.devices)} devices, "
                    f"{result.total_r} R, {result.total_c} C to {output_path}")


class SpefWriter(NetlistWriter):
    """Write parasitic netlist in SPEF (Standard Parasitic Exchange Format).

    SPEF is the industry standard for back-annotating parasitics.
    Note: SPEF does not carry device information — it is meant to be
    read alongside the original schematic netlist. Devices are included
    as comments for reference.
    """

    def write(self, result: ExtractionResult, output_path: Path) -> None:
        lines: list[str] = []

        # Header
        lines.append("*SPEF \"IEEE 1481-1998\"")
        lines.append(f"*DESIGN \"{result.cell_name}\"")
        lines.append("*DATE \"2025-01-01\"")
        lines.append("*VENDOR \"Revolution Semiconductor\"")
        lines.append("*PROGRAM \"rcextract\"")
        lines.append("*VERSION \"0.1.0\"")
        lines.append("*DESIGN_FLOW \"LAYOUT_EXTRACTED\"")
        lines.append("*DIVIDER /")
        lines.append("*DELIMITER :")
        lines.append("*BUS_DELIMITER []")
        lines.append("*T_UNIT 1 NS")
        lines.append("*C_UNIT 1 FF")
        lines.append("*R_UNIT 1 OHM")
        lines.append("*L_UNIT 1 HENRY")
        lines.append("")

        # Name map
        lines.append("*NAME_MAP")
        node_map: dict[str, int] = {}
        idx = 1
        all_nodes: set[str] = set()
        for r in result.resistors:
            all_nodes.add(r.node1)
            all_nodes.add(r.node2)
        for c in result.capacitors:
            all_nodes.add(c.node1)
            all_nodes.add(c.node2)

        for node in sorted(all_nodes):
            node_map[node] = idx
            lines.append(f"*{idx} {_sanitize_node(node)}")
            idx += 1
        lines.append("")

        # Ports
        lines.append("*PORTS")
        for port in result.ports:
            lines.append(f"{port} I")
        lines.append("")

        # D_NET sections — group by net
        nets_seen: set[str] = set()
        for r in result.resistors:
            nets_seen.add(r.net)
        for c in result.capacitors:
            if c.net1:
                nets_seen.add(c.net1)
            if c.cap_type == "coupling" and c.net2:
                nets_seen.add(c.net2)

        for net_name in sorted(nets_seen):
            # Gather R and C for this net (substrate + coupling where this
            # net appears on either side)
            net_resistors = [r for r in result.resistors if r.net == net_name]
            net_caps = [
                c for c in result.capacitors
                if (c.net1 == net_name or
                    (c.cap_type == "coupling" and c.net2 == net_name))
            ]

            total_cap = sum(c.value for c in net_caps)
            lines.append(f"*D_NET {_sanitize_node(net_name)} {total_cap:.4g}")

            # Connections
            lines.append("*CONN")
            if net_name in result.ports:
                lines.append(f"*P {_sanitize_node(net_name)} I")
            # Device pin connections: a device terminal connects to this
            # net when its assigned node equals the net name or is a node
            # that was created within this net's graph.
            for dev in result.devices:
                for term_name, node in dev.terminals.items():
                    if node == net_name:
                        lines.append(
                            f"*I {dev.name}:{term_name} "
                            f"{_sanitize_node(node)} O"
                        )
            lines.append("")

            # Capacitances
            lines.append("*CAP")
            cap_idx = 1
            for cap in net_caps:
                n1 = _spef_node(cap.node1, node_map)
                n2 = _spef_node(cap.node2, node_map)
                lines.append(f"{cap_idx} {n1} {n2} {cap.value:.4g}")
                cap_idx += 1
            lines.append("")

            # Resistances
            lines.append("*RES")
            res_idx = 1
            for r in net_resistors:
                n1 = _spef_node(r.node1, node_map)
                n2 = _spef_node(r.node2, node_map)
                lines.append(f"{res_idx} {n1} {n2} {r.value:.4g}")
                res_idx += 1
            lines.append("")

            lines.append("*END")
            lines.append("")

        output_path.write_text("\n".join(lines))
        logger.info(f"SPEF: wrote to {output_path}")


class SpectreWriter(NetlistWriter):
    """Write parasitic netlist in Cadence Spectre format.

    Spectre syntax:
        subckt cell_name (ports)
        // devices
        I0 (d g s b) model_name param=val
        // parasitics
        R0 (node1 node2) resistor r=value
        C0 (node1 node2) capacitor c=value
        ends cell_name
    """

    def write(self, result: ExtractionResult, output_path: Path) -> None:
        lines: list[str] = []
        lines.append(f"// Parasitic RC extraction: {result.cell_name}")
        lines.append("// Generated by rcextract")
        lines.append(f"// Devices: {len(result.devices)}")
        lines.append(f"// Resistors: {result.total_r}")
        lines.append(f"// Capacitors: {result.total_c}")
        lines.append("")

        # Subcircuit header
        ports_str = " ".join(result.ports)
        lines.append(f"subckt {result.cell_name} ({ports_str})")
        lines.append("")

        # Devices
        if result.devices:
            lines.append("// --- Devices ---")
            for dev in result.devices:
                line = _format_spectre_device(dev)
                lines.append(line)
            lines.append("")

        # Resistors
        if result.resistors:
            r_count = 0
            lines.append("// --- Parasitic Resistances ---")
            for resistor in result.resistors:
                r_count += 1
                node1 = _sanitize_node(resistor.node1)
                node2 = _sanitize_node(resistor.node2)
                lines.append(
                    f"R{r_count} ({node1} {node2}) resistor r={resistor.value:.4g}"
                )
            lines.append("")

        # Capacitors
        if result.capacitors:
            c_count = 0
            lines.append("// --- Parasitic Capacitances ---")
            for cap in result.capacitors:
                c_count += 1
                node1 = _sanitize_node(cap.node1)
                node2 = _sanitize_node(cap.node2)
                lines.append(
                    f"C{c_count} ({node1} {node2}) capacitor c={cap.value:.4g}f"
                )
            lines.append("")

        lines.append(f"ends {result.cell_name}")
        lines.append("")

        output_path.write_text("\n".join(lines))
        logger.info(f"Spectre: wrote {len(result.devices)} devices, "
                    f"{result.total_r} R, {result.total_c} C to {output_path}")


class VacaskWriter(NetlistWriter):
    """Write parasitic netlist in VACASK format.

    VACASK uses a Spectre-like syntax with explicit device loading.
    Resistors and capacitors are Verilog-A OSDI devices that must be
    loaded before use.

    Output format:
        // title
        load "resistor.osdi"
        load "capacitor.osdi"

        model res_par resistor
        model cap_par capacitor

        subckt cell_name (ports)
        // devices
        m1 (d g s b) model_name param=val
        // parasitics
        r1 (node1 node2) res_par r=value
        c1 (node1 node2) cap_par c=value
        ends cell_name
    """

    def write(self, result: ExtractionResult, output_path: Path) -> None:
        lines: list[str] = []
        lines.append(f"// Parasitic RC extraction: {result.cell_name}")
        lines.append("// Generated by rcextract")
        lines.append(f"// Devices: {len(result.devices)}")
        lines.append(f"// Resistors: {result.total_r}")
        lines.append(f"// Capacitors: {result.total_c}")
        lines.append("")

        # Load parasitic device models
        lines.append("// Load parasitic element devices")
        lines.append('load "resistor.osdi"')
        lines.append('load "capacitor.osdi"')
        lines.append("")
        lines.append("// Parasitic element models")
        lines.append("model res_par resistor")
        lines.append("model cap_par capacitor")
        lines.append("")

        # Subcircuit header
        ports_str = " ".join(result.ports)
        lines.append(f"subckt {result.cell_name} ({ports_str})")
        lines.append("")

        # Devices
        if result.devices:
            lines.append("  // --- Devices ---")
            for dev in result.devices:
                line = _format_vacask_device(dev)
                lines.append(f"  {line}")
            lines.append("")

        # Resistors
        if result.resistors:
            r_count = 0
            lines.append("  // --- Parasitic Resistances ---")
            for resistor in result.resistors:
                r_count += 1
                node1 = _sanitize_node(resistor.node1)
                node2 = _sanitize_node(resistor.node2)
                lines.append(
                    f"  r{r_count} ({node1} {node2}) res_par r={resistor.value:.4g}"
                )
            lines.append("")

        # Capacitors
        if result.capacitors:
            c_count = 0
            lines.append("  // --- Parasitic Capacitances ---")
            for cap in result.capacitors:
                c_count += 1
                node1 = _sanitize_node(cap.node1)
                node2 = _sanitize_node(cap.node2)
                lines.append(
                    f"  c{c_count} ({node1} {node2}) cap_par c={cap.value:.4g}f"
                )
            lines.append("")

        lines.append(f"ends {result.cell_name}")
        lines.append("")

        output_path.write_text("\n".join(lines))
        logger.info(f"VACASK: wrote {len(result.devices)} devices, "
                    f"{result.total_r} R, {result.total_c} C to {output_path}")


# ---------------------------------------------------------------------------
# Format helpers
# ---------------------------------------------------------------------------


def _format_spice_device(dev: DeviceInstance) -> str:
    """Format a device instance as a SPICE subcircuit call.

    SPICE convention: XI0 node1 node2 ... model_name param=val param=val
    """
    # Build terminal node list in a deterministic order
    # Standard MOSFET order: D G S B
    terminal_order = _get_terminal_order(dev.model)
    nodes = []
    for term in terminal_order:
        if term in dev.terminals:
            nodes.append(_sanitize_node(dev.terminals[term]))
    # Any remaining terminals not in the standard order
    for term, node in dev.terminals.items():
        if term not in terminal_order:
            nodes.append(_sanitize_node(node))

    nodes_str = " ".join(nodes)
    params_str = " ".join(f"{k}={_format_param(v)}" for k, v in dev.params.items())

    prefix = "X" if not dev.name.startswith("X") else ""
    line = f"{prefix}{dev.name} {nodes_str} {dev.model}"
    if params_str:
        line += f" {params_str}"
    return line


def _format_spectre_device(dev: DeviceInstance) -> str:
    """Format a device instance in Spectre syntax.

    Spectre convention: I0 (node1 node2 ...) model_name param=val
    """
    terminal_order = _get_terminal_order(dev.model)
    nodes = []
    for term in terminal_order:
        if term in dev.terminals:
            nodes.append(_sanitize_node(dev.terminals[term]))
    for term, node in dev.terminals.items():
        if term not in terminal_order:
            nodes.append(_sanitize_node(node))

    nodes_str = " ".join(nodes)
    params_str = " ".join(f"{k}={_format_param(v)}" for k, v in dev.params.items())

    line = f"{dev.name} ({nodes_str}) {dev.model}"
    if params_str:
        line += f" {params_str}"
    return line


def _format_vacask_device(dev: DeviceInstance) -> str:
    """Format a device instance in VACASK syntax.

    VACASK convention: name (node1 node2 ...) model_name param=val
    Same as Spectre but instance names are lowercase by convention.
    """
    terminal_order = _get_terminal_order(dev.model)
    nodes = []
    for term in terminal_order:
        if term in dev.terminals:
            nodes.append(_sanitize_node(dev.terminals[term]))
    for term, node in dev.terminals.items():
        if term not in terminal_order:
            nodes.append(_sanitize_node(node))

    nodes_str = " ".join(nodes)
    params_str = " ".join(f"{k}={_format_param(v)}" for k, v in dev.params.items())

    name = dev.name.lower()
    line = f"{name} ({nodes_str}) {dev.model}"
    if params_str:
        line += f" {params_str}"
    return line


def _get_terminal_order(model: str) -> list[str]:
    """Get standard terminal order for a device model."""
    model_lower = model.lower()
    if "nmos" in model_lower or "pmos" in model_lower or "fet" in model_lower:
        return ["D", "G", "S", "B"]
    elif "npn" in model_lower or "pnp" in model_lower:
        return ["C", "B", "E"]
    elif "cap" in model_lower or "mimcap" in model_lower:
        return ["PLUS", "MINUS"]
    elif "res" in model_lower or "rppd" in model_lower or "rhigh" in model_lower:
        return ["PLUS", "MINUS", "B"]
    elif "diode" in model_lower:
        return ["A", "C"]
    else:
        return []


def _format_param(value) -> str:
    """Format a parameter value for netlist output."""
    if isinstance(value, float):
        if abs(value) < 1e-12:
            return "0"
        elif abs(value) < 1e-6:
            return f"{value * 1e9:.4g}n"
        elif abs(value) < 1e-3:
            return f"{value * 1e6:.4g}u"
        elif abs(value) < 1:
            return f"{value * 1e3:.4g}m"
        else:
            return f"{value:.4g}"
    return str(value)


def _sanitize_node(name: str) -> str:
    """Sanitize a node name for netlist output."""
    return name.replace(":", "_").replace(" ", "_").replace("/", "_")


def _spef_node(name: str, node_map: dict[str, int]) -> str:
    """Get SPEF node reference."""
    if name in node_map:
        return f"*{node_map[name]}"
    return _sanitize_node(name)


def get_writer(format_name: str) -> NetlistWriter:
    """Get a netlist writer by format name.

    Args:
        format_name: One of "spice", "spef", "spectre", "vacask".

    Returns:
        Appropriate NetlistWriter instance.
    """
    writers = {
        "spice": SpiceWriter,
        "spef": SpefWriter,
        "spectre": SpectreWriter,
        "vacask": VacaskWriter,
    }
    if format_name not in writers:
        raise ValueError(f"Unknown format '{format_name}'. Available: {list(writers.keys())}")
    return writers[format_name]()
